# Generated by Django 4.0.4 on 2022-05-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_player_task_alter_item_cell_cell_unique position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='error',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
