# Generated by Django 4.0.4 on 2022-05-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_player_inventory_player_unlocked_alter_task_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='inventory',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='unlocked',
            field=models.CharField(blank=True, default='FAKE', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
