# Generated by Django 4.0.4 on 2022-05-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_player_inventory_alter_player_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='fake',
            field=models.BooleanField(default=False),
        ),
    ]
